### ISSUE TITLE
As a dev I want to have module that provides similarity information for music tracks. [1]

### ISSUE THREAD

**Issue by perguth** [peermusic/user-stories#24]
- [x] update new req/res format of the scrapping server

From the previous sprint:
- [x] Takes music track name (artist, title,...) as argument
- [x] Request results in a list of similar music tracks
- [x] This module broadens the search to provide a certain amount of results (track -> artist -> album -> genre)
- [x] Requests that information from the scraping server (until that code gets extracted into its own module, see #29)
- [x] Saves information locally for future requests, see #17 
- [x] Wait for peermusic/user-stories#21 and use the resulting server

Start a repo and write a module for this functionality.
